import zipfile
import os

files_to_zip = [
    'src/app/pricing/page.tsx',
    'src/app/pricing/PricingClient.tsx',
    'src/app/products/page.tsx',
    'src/components/layout/Footer.tsx',
    'src/app/admin/(dashboard)/pricing/page.tsx',
    'src/app/admin/(dashboard)/pricing/PricingAdminClient.tsx',
    'src/app/admin/(dashboard)/pricing/ComboForm.tsx',
    'src/app/admin/(dashboard)/website/page.tsx',
    'src/app/admin/(dashboard)/website/WebsiteClient.tsx',
    'src/app/api/admin/settings/route.ts',
    'src/app/api/settings/public/route.ts',
    'src/app/admin/(dashboard)/footer/page.tsx',
    'src/app/refund/page.tsx',
    'src/app/admin/(dashboard)/pricing/[id]/EditPlanForm.tsx',
    'src/app/admin/(dashboard)/pricing/[id]/page.tsx',
    'src/app/admin/(dashboard)/orders/page.tsx',
    'src/app/admin/(dashboard)/orders/OrdersClient.tsx',
    'src/app/offer/[id]/page.tsx',
    'src/app/login/page.tsx',
    'src/app/register/page.tsx',
    'src/app/forgot-password/page.tsx',
    'src/app/reset-password/page.tsx',
    'src/app/demo/page.tsx',
    'src/app/dashboard/page.tsx',
    'src/app/onboarding/page.tsx',
    'src/app/onboarding/actions.ts',
    'src/app/onboarding/OnboardingForm.tsx',
    'src/app/admin/(dashboard)/clients/page.tsx',
    'src/app/admin/(dashboard)/clients/ClientsClient.tsx',
    'src/app/api/seed-pricing/route.ts',
    'src/app/admin/(dashboard)/billing/page.tsx',
    'src/app/admin/(dashboard)/billing/BillingClient.tsx',
    'src/components/layout/ClientLayoutWrapper.tsx',
    'src/components/layout/Navbar.tsx',
    'src/components/LicenseKey.tsx',
    'src/components/LoadingScreen.tsx',
    'src/app/marketing/clients/page.tsx',
    'src/app/api/auth/register/route.ts',
    'public/logos/logo.svg',
    'public/logos/logo-light.svg',
    'public/logos/icon.svg',
    'src/app/icon.svg',
    'auth.ts',
    'src/components/FaqSection.tsx',
    'src/app/faq/page.tsx',
    'src/app/terms/page.tsx',
    'src/app/privacy/page.tsx',
    'src/app/careers/page.tsx',
    'src/app/admin/(dashboard)/careers/page.tsx',
    'src/app/admin/(dashboard)/careers/CareersAdminClient.tsx',
    'src/app/admin/(dashboard)/staff/page.tsx',
    'src/app/admin/(dashboard)/layout.tsx',
    'src/app/api/admin/restaurant-action/route.ts',
    'src/app/api/admin/billing/approve/route.ts',
    'src/app/api/billing/subscription-payment/route.ts',
    'src/app/dashboard/billing/checkout/page.tsx',
    'src/app/api/license/verify/route.ts',
    'src/app/api/restaurant/sync/route.ts',
    'prisma/schema.prisma',
    'src/middleware.ts',
    'src/app/api/admin/login/route.ts',
    'src/app/api/admin/staff/route.ts',
    'src/app/api/admin/testimonials/route.ts',
    'src/app/api/admin/settings/upload-qr/route.ts',
    'src/app/api/admin/settings/test-ebilling/route.ts',
    'src/app/api/admin/client-logos/route.ts',
    'src/app/api/admin/client-logos/[id]/route.ts',
    'src/app/api/admin/orders/route.ts',
    'src/app/api/admin/orders/[id]/route.ts',
    'src/app/api/admin/orders/[id]/sync/route.ts',
    'src/app/api/admin/faq/route.ts',
    'src/app/api/admin/contact/route.ts',
    'src/app/api/support/tickets/route.ts',
    'src/app/api/contact/route.ts',
    'src/app/admin/(dashboard)/support/SupportClient.tsx',
    'src/app/admin/(dashboard)/contact/ContactClient.tsx',
    'src/app/dashboard/billing/page.tsx',
    'src/app/dashboard/billing/plans/PlansClient.tsx',
    'src/app/contact/page.tsx',
    'src/app/contact/ContactClient.tsx',
    'DrestroPOS/clear_orphaned_pos.php',
    'DrestroPOS/find_db.php'
]

zip_name = 'drestro_final_combined_all_updates.zip'

with zipfile.ZipFile(zip_name, 'w', zipfile.ZIP_DEFLATED) as zipf:
    for file in files_to_zip:
        if os.path.exists(file):
            zipf.write(file, arcname=file)
            print(f"Added: {file}")
        else:
            print(f"Missing: {file}")

print(f"Created {zip_name} successfully containing all updates.")
